name: account_center_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.8.0
  url_launcher: ^6.3.1
  web: ^1.1.0
  provider: ^6.1.2
  flutter_iconpicker: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
